spring.application.name=test-rest-api

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
jpa.hibernate.ddl-auto=update  # create, update, validate (use 'none' in prod)
jpa.show-sql=true
jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#/actuator/health
#/actuator/metrics
#/actuator/env
#/actuator/beans
#/actuator/threaddump
management.endpoints.web.exposure.include=*